name: ROS2 Simulation Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: osrf/ros:foxy-desktop
      options: --gpus all

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up ROS 2 environment
      run: |
        source /opt/ros/foxy/setup.bash
        mkdir -p ~/ros2_ws/src
        cd ~/ros2_ws
        colcon build

    - name: Run ROS 2 tests
      run: |
        source ~/ros2_ws/install/setup.bash
        ros2 run your_package your_node  # Remplacez "your_package" et "your_node"
